apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mortality_band_service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mortality_band_service
    spec:
      containers:
      - name: mortality_band_service
        image: IMAGE_NAME_TO_BE_REPLACED
        command: ["/bin/sh","-c"]
        args: ["uwsgi --emperor /etc/uwsgi/sites --daemonize /var/log/uwsgi/uwsgi.log; nginx -g 'daemon off;'"]
        env:
        - name: PORT
          value: "80"
        - name: DJANGO_SETTINGS_MODULE
          value: SETTINGS_NAME_TO_BE_REPLACED
        ports:
        - name: ms-line-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /mortality_band_service/health
            port: ms-line-port
          initialDelaySeconds: 120
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            path: /mortality_band_service/health
            port: ms-line-port
          initialDelaySeconds: 120
          timeoutSeconds: 180
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-mortality_band_service
spec:
  ports:
  - name: http
    port: 80
    targetPort: ms-line-port
    protocol: TCP
  selector:
    app: mortality_band_service
  type: ClusterIP